INSERT INTO CONSULTORIO(ID,  NUMERO) VALUES(1, 10);
INSERT INTO CONSULTORIO(ID,  NUMERO) VALUES(2, 11);
INSERT INTO CONSULTORIO(ID,  NUMERO) VALUES(3, 12);
INSERT INTO CONSULTORIO(ID,  NUMERO) VALUES(4, 13);

INSERT INTO MEDICO(ID, CRM, IDADE, NOME) VALUES(1, 1010, 40, 'PAULA');
INSERT INTO MEDICO(ID, CRM, IDADE, NOME) VALUES(2, 1111, 40, 'FELIPE');
INSERT INTO MEDICO(ID, CRM, IDADE, NOME) VALUES(3, 1212, 40, 'RODRIGO');
INSERT INTO MEDICO(ID, CRM, IDADE, NOME) VALUES(4, 1313, 40, 'PRISCILA');


SELECT * FROM CONSULTA;

SELECT * FROM CONSULTORIO;

SELECT * FROM MEDICO;